// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACvfVdj4xDwnKwsiKO3NwyV6ogKcsuko0',
    appId: '1:1007735748657:web:0765979ef9358f83263d10',
    messagingSenderId: '1007735748657',
    projectId: 'weather-6d9f3',
    authDomain: 'weather-6d9f3.firebaseapp.com',
    storageBucket: 'weather-6d9f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUeT8pPrb168575K9vYkyX5lS4K94Qbrc',
    appId: '1:1007735748657:android:55d13ed439c3c93c263d10',
    messagingSenderId: '1007735748657',
    projectId: 'weather-6d9f3',
    storageBucket: 'weather-6d9f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy7TrMpi5EeFxaBs3dMw97FVtZtHVgr-c',
    appId: '1:1007735748657:ios:efe4ab8b876b94f8263d10',
    messagingSenderId: '1007735748657',
    projectId: 'weather-6d9f3',
    storageBucket: 'weather-6d9f3.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy7TrMpi5EeFxaBs3dMw97FVtZtHVgr-c',
    appId: '1:1007735748657:ios:efe4ab8b876b94f8263d10',
    messagingSenderId: '1007735748657',
    projectId: 'weather-6d9f3',
    storageBucket: 'weather-6d9f3.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACvfVdj4xDwnKwsiKO3NwyV6ogKcsuko0',
    appId: '1:1007735748657:web:e425779d4371e784263d10',
    messagingSenderId: '1007735748657',
    projectId: 'weather-6d9f3',
    authDomain: 'weather-6d9f3.firebaseapp.com',
    storageBucket: 'weather-6d9f3.firebasestorage.app',
  );
}
